### ISSUE TITLE
Introduce ZPM support

### ISSUE THREAD

**Issue by evshvarov** [devecchijr/apiPub#1]
[Learn more on ZPM](https://openexchange.intersystems.com/package/ObjectScript-Package-Manager)

**Comment by devecchijr** [comment]
> [Learn more on ZPM](https://openexchange.intersystems.com/package/ObjectScript-Package-Manager)

Now it's ZPM compatible. Thanks a lot for your feedback

**Comment by evshvarov** [comment]
Fantastic! Thanks for the very helpful lib!
